services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/production/nginx/Dockerfile
    image: aris1991/laravel-api:nginx

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/production/php-fpm/Dockerfile
      target: production
    image: aris1991/laravel-api:php-fpm

  php-cli:
    build:
      context: .
      dockerfile: ./docker/production/php-cli/Dockerfile
    image: aris1991/laravel-api:php-cli

  frontend:
    build: 
      context: .
      dockerfile: production/react/Dockerfile
    image: aris1991/laravel-api:frontend