services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/production/nginx/Dockerfile
    image: aris1991/language-practise:nginx

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/production/php-fpm/Dockerfile
      target: production
    image: aris1991/language-practise:php-fpm

  php-cli:
    build:
      context: .
      dockerfile: ./docker/production/php-cli/Dockerfile
    image: aris1991/language-practise:php-cli

  fast-api:
    build: 
      context: .
      dockerfile: ./docker/production/fast-api/Dockerfile
    image: aris1991/language-practise:fast-api

  frontend:
    build: 
      context: .
      dockerfile: ./docker/production/react/Dockerfile
    image: aris1991/language-practise:frontend