name: Docker Compose Action

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          compose-file: "./compose.prod.yaml"

      - name: Build the Docker image
        run: docker compose -f compose.prod.yaml build

      - name: Push image to Dockerhub
        run: |
          docker login -u aris1991 -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker compose -f compose.prod.yaml push

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      
      - name: Connect to EC2 instance
        env:
          PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem
          ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} << 'EOF'
                cd ~/language_practise
                echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username aris1991 --password-stdin
                docker compose pull
                docker compose up -d
                docker system prune -a --volumes -f
          EOF
      
      - name: Ping Host
        run: |
          bash ${{ github.workspace }}/.github/workflows/scripts/check-ping.sh langpractise.zapto.org

