name: Docker Compose Action

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./compose.prod.yaml"

      - name: Build the Docker image
        run: docker compose -f compose.prod.yaml build

      - name: Push image to Dockerhub
        run: |
          docker login -u aris1991 -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker compose -f compose.prod.yaml push

  deploy:
    needs: build
    runs-on: [aws-ec2]

    steps:
      - name: Delete old containers 
        uses: hoverkraft-tech/compose-action@v2.0.1
        run: |
          docker-compose down
          docker container prune

      - name: |
             docker login -u aris1991 -p ${{ secrets.DOCKERHUB_TOKEN }}
             Pull Images from dockerhub
        run: docker-compose pull

      - name: Start services
        run: docker-compose up -d
