name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker-compose -f compose.prod.yaml up -d --build 
    - name: Push image to Dockerhub
      run: |
        docker login -u aris1991 -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker-compose -f compose.prod.yaml push
